services:
  database-layer:
    image: postgres
    container_name: database-layer
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: dbname

    volumes:
      - database-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: on-failure

  # Backend (Express)
  backend:
    depends_on:
      - database-layer
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    container_name: backend
    ports:
      - '4004:4004'
    command: npm run dev
    restart: on-failure

  # Frontend (React)
  frontend:
    build: ./frontend
    container_name: frontend-container
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - backend

  adminer:
    image: adminer
    container_name: adminer-docker
    depends_on:
      - database-layer
    ports:
      - '8082:8080'
    restart: on-failure

volumes:
  database-volume:
